spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/bancoxyz

core:
  service:
    url: http://core-service:8080

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true

resilience4j:
  circuitbreaker:
    instances:
      coreServiceClient:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        wait-duration-in-open-state: 10s
        failure-rate-threshold: 50
  timelimiter:
    instances:
      coreServiceClient:
        timeout-duration: 3s

management:
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers,metrics
  health:
    circuitbreakers:
      enabled: true
